project:
  type: website
  render: 
    - "index.qmd"
    - "*/*/index.qmd"
    - "preprints.qmd"
    - "by-statsds-topic.qmd"

website:
  title: "SCORE Module Repository Testing Site"
  page-footer: "Maintained by No one"
  cookie-consent: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - by-statsds-topic.qmd
      - preprints.qmd
      - href: https://data.scorenetwork.org/
        text: Data Repository
      - href: https://scorenetwork.org/index.html
        text: SCORE Network
    right:
      - icon: twitter
        href: https://twitter.com/scorenetworkorg
      - icon: linkedin
        href: https://www.linkedin.com/company/scorenetworkorg/
  sidebar:
    contents: auto
    collapse-level: 1
  repo-url: https://github.com/iramler/score_test
  repo-actions: [edit, issue]

format:
  html:
    theme:
      - cosmo
      - score.scss
    toc: true

execute:
  freeze: auto
